---
- stat:
    path: /srv/limesurvey
  register: limesurvey_dir_exists  

- name: Update repositories cache
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  changed_when: False

- import_tasks: install.yml
  when: not limesurvey_dir_exists.stat.exists

- import_tasks: configure.yml

